### ISSUE TITLE
Slides toevoegen in OKO figurenboek

### ISSUE THREAD

**Issue by SBorsboom** [ggdatascience/rapportage_monitor_gmj#38]
Ik probeerde nog OKO vragen (de facultatieve) toe te voegen aan het einde van het figurenboek, maar dat lukt niet. Ik krijg de volgende melding. 

Error in `pmap()`:
ℹ In index: 1.
Caused by error in `pmap()`:
ℹ In index: 110.
Caused by error in `cell_limits()`:
! rows[1] <= rows[2] is not TRUE

Heet iemand ervaring met het toevoegen van slides?

**Comment by STVermeulen** [comment]
Deze error herken ik niet. Het is mogelijk om zelf vragen toe te voegen. Zou je je template en configuratie kunnen delen?

**Comment by GuidoWillekens** [comment]
**Ik heb dezelfde error;**

> # Inladen van alle tabbladen van de Excel configuratie
> configuratie <- padnaam_configuratie %>% 
+   excel_sheets() %>% 
+   set_names() %>% 
+   map(read_excel, path = padnaam_configuratie)
> # Maken van figurenboeken
> pmap(.l = configuratie$Rapportconfiguratie,
+      .f = rapportage_maken, data = data, configuratie = configuratie, template = '2. Template Figurenboek.pptx')
Error in `pmap()`:
ℹ In index: 1.
Caused by error in `pmap()`:
ℹ In index: 2.
Caused by error in `cell_limits()`:
! rows[1] <= rows[2] is not TRUE
Run `rlang::last_trace()` to see where the error occurred.
